spring:
  datasource: #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/daka?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 12345678
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5
mybatis:
  mapper-locations: classpath*:com/ligouzi/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

business:
  host: http://img.ligouzi.com/